TDL-12464: Added support for handling the duplicate headers in the CS…
singer-io/tap-s3-csv pull request #30
Opened 2021-05-07 14:49 UTC by karanpanchal-crest

…V file

# Description of change
Duplicate Headers
1. If Duplicate headers are present in CSV we move its value to **_sdc_extra** column/field
2. We removed the dependency of singer-encodings to read CSV, we developed the code to read CSV in tap itself.

# Manual QA steps
 - Verified the CSV reading with intact row values, lesser row values than a number of headers, and more row values than a number of headers in the CSV file.
 - Made sure that unit test cases cover all different scenarios to handle duplicate headers.
 
# Risks
 - No Risks
 
# Rollback steps
 - revert this branch

2021-05-11 12:43 UTC, dbshah1212 approved these changes

2021-05-14 15:18 UTC, KAllan357 requested changes
I'd prefer not to remove our usage of the shared singer-encodings library - I think changes like this should be there so that we can share it across our other CSV-consuming taps. We should talk about this.

2021-05-18 15:46 UTC, karanpanchal-crest commented
> I'd prefer not to remove our usage of the shared singer-encodings library - I think changes like this should be there so that we can share it across our other CSV-consuming taps. We should talk about this.

@KAllan357 As discussed in the sync up, we have added the code in the singer-encoding library for duplicate header support. We have also made the tap compatible with the upcoming version of singer-encoding library
PR for the singer-encoding library: https://github.com/singer-io/singer-encodings/pull/14

2021-05-27 20:13 UTC, KAllan357 commented
I've released singer-encodings 0.1.0 which should allow these tests to pass.

2021-06-01 13:24 UTC, KAllan357 approved these changes

2021-06-01 13:24 UTC, merged